#include <parameters/param.h>

/**
 * @group Multicopter NMPC Control
 */
PARAM_DEFINE_INT32(NMPC_ABS_POS, -1);

/**
 * @group Multicopter NMPC Control
 */
PARAM_DEFINE_FLOAT(NMPC_G1_XMM, -1.0e30f);

/**
 * @group Multicopter NMPC Control
 */
PARAM_DEFINE_FLOAT(NMPC_G1_YMM, -1.0e30f);

/**
 * @group Multicopter NMPC Control
 */
PARAM_DEFINE_FLOAT(NMPC_G1_ZMM, -1.0e30f);

/**
 * @group Multicopter NMPC Control
 */
PARAM_DEFINE_FLOAT(NMPC_G2_XMM, -1.0e30f);

/**
 * @group Multicopter NMPC Control
 */
PARAM_DEFINE_FLOAT(NMPC_G2_YMM, -1.0e30f);

/**
 * @group Multicopter NMPC Control
 */
PARAM_DEFINE_FLOAT(NMPC_G2_ZMM, -1.0e30f);

/**
 * @group Multicopter NMPC Control
 */
PARAM_DEFINE_INT32(NMPC_SP_COUNT, -1);

PARAM_DEFINE_FLOAT(NMPC_S0_PX, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S0_PY, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S0_PZ, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S0_VX, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S0_VY, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S0_VZ, -1.0e30f);
PARAM_DEFINE_INT32(NMPC_S0_HAS_T, -1);
PARAM_DEFINE_FLOAT(NMPC_S0_T, -1.0e30f);
PARAM_DEFINE_INT32(NMPC_S0_HAS_X, -1);
PARAM_DEFINE_FLOAT(NMPC_S0_XLIM, -1.0e30f);
PARAM_DEFINE_INT32(NMPC_S0_CTRL, -1);
PARAM_DEFINE_INT32(NMPC_S0_MODE, -1);

PARAM_DEFINE_FLOAT(NMPC_S1_PX, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S1_PY, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S1_PZ, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S1_VX, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S1_VY, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S1_VZ, -1.0e30f);
PARAM_DEFINE_INT32(NMPC_S1_HAS_T, -1);
PARAM_DEFINE_FLOAT(NMPC_S1_T, -1.0e30f);
PARAM_DEFINE_INT32(NMPC_S1_HAS_X, -1);
PARAM_DEFINE_FLOAT(NMPC_S1_XLIM, -1.0e30f);
PARAM_DEFINE_INT32(NMPC_S1_CTRL, -1);
PARAM_DEFINE_INT32(NMPC_S1_MODE, -1);

PARAM_DEFINE_FLOAT(NMPC_S2_PX, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S2_PY, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S2_PZ, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S2_VX, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S2_VY, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S2_VZ, -1.0e30f);
PARAM_DEFINE_INT32(NMPC_S2_HAS_T, -1);
PARAM_DEFINE_FLOAT(NMPC_S2_T, -1.0e30f);
PARAM_DEFINE_INT32(NMPC_S2_HAS_X, -1);
PARAM_DEFINE_FLOAT(NMPC_S2_XLIM, -1.0e30f);
PARAM_DEFINE_INT32(NMPC_S2_CTRL, -1);
PARAM_DEFINE_INT32(NMPC_S2_MODE, -1);

PARAM_DEFINE_FLOAT(NMPC_S3_PX, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S3_PY, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S3_PZ, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S3_VX, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S3_VY, -1.0e30f);
PARAM_DEFINE_FLOAT(NMPC_S3_VZ, -1.0e30f);
PARAM_DEFINE_INT32(NMPC_S3_HAS_T, -1);
PARAM_DEFINE_FLOAT(NMPC_S3_T, -1.0e30f);
PARAM_DEFINE_INT32(NMPC_S3_HAS_X, -1);
PARAM_DEFINE_FLOAT(NMPC_S3_XLIM, -1.0e30f);
PARAM_DEFINE_INT32(NMPC_S3_CTRL, -1);
PARAM_DEFINE_INT32(NMPC_S3_MODE, -1);
